/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package solicitudtaller;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Sides;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel San Nicolas
 */
public class FrmSolicitud extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    FrmBucarBien bus = new FrmBucarBien(this, true);
    Conexion z = new Conexion();
    
    int t = 0; //bandera para el tipode bien
    /**
     * Creates new form FrmSolicitud
     */
    public FrmSolicitud() {
        initComponents();
        configGrilla();
        cargarRubro();
        cargarPrograma();
        cargarArea();
        RbBien.setSelected(true);
        responsable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlSolicitud = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblPrograma = new javax.swing.JLabel();
        lblRubro = new javax.swing.JLabel();
        PnlTipo = new javax.swing.JPanel();
        RbBien = new javax.swing.JRadioButton();
        RbServicio = new javax.swing.JRadioButton();
        txtNumero = new javax.swing.JTextField();
        cboPrograma = new javax.swing.JComboBox();
        cboRubro = new javax.swing.JComboBox();
        lblResponsable = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtArticulo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        pnlRegistro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        PnlDescripcion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblRubro1 = new javax.swing.JLabel();
        cboArea = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlSolicitud.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitud de Bienes"));

        lblNumero.setText("Número");

        lblPrograma.setText("Programa");

        lblRubro.setText("Rubro");

        PnlTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        PnlTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlTipoMouseClicked(evt);
            }
        });

        RbBien.setText("Bien");
        RbBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbBienActionPerformed(evt);
            }
        });

        RbServicio.setText("Servicio");
        RbServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlTipoLayout = new javax.swing.GroupLayout(PnlTipo);
        PnlTipo.setLayout(PnlTipoLayout);
        PnlTipoLayout.setHorizontalGroup(
            PnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RbBien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RbServicio)
                .addGap(14, 14, 14))
        );
        PnlTipoLayout.setVerticalGroup(
            PnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTipoLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(PnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbBien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RbServicio, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        cboPrograma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblResponsable.setText("Responsable");

        txtResponsable.setEnabled(false);
        txtResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsableActionPerformed(evt);
            }
        });

        lblCantidad.setText("Cantidad");

        lblDescripcion.setText("Descripción");

        lblId.setText("id");

        txtId.setEnabled(false);

        txtArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtArticuloKeyReleased(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });

        pnlRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        Tabla.setModel(modelo);
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnAdd.setText("Add");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnAddKeyReleased(evt);
            }
        });

        PnlDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout PnlDescripcionLayout = new javax.swing.GroupLayout(PnlDescripcion);
        PnlDescripcion.setLayout(PnlDescripcionLayout);
        PnlDescripcionLayout.setHorizontalGroup(
            PnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        PnlDescripcionLayout.setVerticalGroup(
            PnlDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDescripcionLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");

        btnCancelar.setText("Cancelar");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblRubro1.setText("Área");

        cboArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlSolicitudLayout = new javax.swing.GroupLayout(PnlSolicitud);
        PnlSolicitud.setLayout(PnlSolicitudLayout);
        PnlSolicitudLayout.setHorizontalGroup(
            PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSolicitudLayout.createSequentialGroup()
                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlSolicitudLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PnlDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PnlSolicitudLayout.createSequentialGroup()
                                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PnlSolicitudLayout.createSequentialGroup()
                                        .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNumero)
                                            .addComponent(lblRubro)
                                            .addComponent(lblPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblRubro1))
                                        .addGap(21, 21, 21)
                                        .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboPrograma, javax.swing.GroupLayout.Alignment.TRAILING, 0, 176, Short.MAX_VALUE)
                                            .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cboRubro, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cboArea, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)
                                        .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PnlSolicitudLayout.createSequentialGroup()
                                                .addComponent(lblResponsable)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(PnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PnlSolicitudLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtId)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlSolicitudLayout.createSequentialGroup()
                                        .addComponent(lblDescripcion)
                                        .addGap(0, 189, Short.MAX_VALUE))
                                    .addGroup(PnlSolicitudLayout.createSequentialGroup()
                                        .addComponent(txtArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantidad)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(PnlSolicitudLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnlSolicitudLayout.setVerticalGroup(
            PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSolicitudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlSolicitudLayout.createSequentialGroup()
                        .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblPrograma)
                            .addComponent(cboPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblRubro)
                    .addComponent(cboRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResponsable)
                    .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblRubro1)
                    .addComponent(cboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(lblDescripcion)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbBienActionPerformed
        t = 1;
        tipo();
    }//GEN-LAST:event_RbBienActionPerformed

    private void RbServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbServicioActionPerformed
        t = 2;
        tipo();
    }//GEN-LAST:event_RbServicioActionPerformed

    private void txtResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsableActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(recorerGrilla() !=  0){
            
        }else
            cargaGrilla();
        
        txtArticulo.setText(null);
        txtCantidad.setText(null);
        btnAdd.setEnabled(false);
        txtArticulo.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticuloKeyReleased
        bus.setVisible(true);
        cargarItem();
        txtCantidad.requestFocus(); 
        addactive();
    }//GEN-LAST:event_txtArticuloKeyReleased

    private void PnlTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlTipoMouseClicked
      
    }//GEN-LAST:event_PnlTipoMouseClicked

    private void btnAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyReleased
        
    }//GEN-LAST:event_btnAddKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        addactive();
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        
    }//GEN-LAST:event_btnAddKeyPressed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    insertar();
}//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAreaActionPerformed
        
    }//GEN-LAST:event_cboAreaActionPerformed

    private void cargarItem(){
        txtId.setText(FrmBucarBien.vcod);
        txtArticulo.setText(FrmBucarBien.vdes);
    }
    
    private void configGrilla(){
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Cantidad");
    }
    
    private void responsable(){
        
        try {
            String sql = "SELECT concat(nombre,' ', apellido) as responsable FROM usuario where username like '%"+FrmAcceso.usuario+"%'";
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            z.rs.next();
            txtResponsable.setText(z.rs.getString("responsable").toString());
        } catch (SQLException ex) {
            Logger.getLogger(FrmSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void cargaGrilla(){
        String[] datos = new String[3];
        datos[0] = txtId.getText().toString();
        datos[1] = txtArticulo.getText().toString();
        datos[2] = txtCantidad.getText().toString();
        modelo.addRow(datos);
    }

    //Este metodo verifica en una grill el que exista cargado el id de un articulo y en ese caso suma las cantidades
   private int recorerGrilla(){
       int aux = 0;
            for(int i = 0; i < Tabla.getRowCount(); i++){
                if(Integer.parseInt(modelo.getValueAt(i, 0).toString()) == Integer.parseInt( txtId.getText().toString())){
                    aux = Integer.parseInt(modelo.getValueAt(i, 2).toString()) + Integer.parseInt( txtCantidad.getText() );
                    modelo.setValueAt(aux, i, 2);
                    
                }
                System.out.print(modelo.getValueAt(i, 0)); 
                
            }
            System.out.println("La cantidad de fila es de "+Tabla.getRowCount());
            
       return aux;
   }
    
    private void cargarRubro(){
        try {
            String sql = "SELECT * FROM rubro order by descripcion ";
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            cboRubro.removeAllItems();
            while (z.rs.next()) {
                cboRubro.addItem(z.rs.getString("descripcion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void cargarArea(){
        try {
            String sql = "SELECT * FROM area order by descripcion ";
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            cboArea.removeAllItems();
            while (z.rs.next()) {
                cboArea.addItem(z.rs.getString("descripcion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void tipo(){
        switch (t) {
            case 1:  RbBien.setSelected(true);
                     RbServicio.setSelected(false);
                     break;
            case 2:  RbBien.setSelected(false);
                     RbServicio.setSelected(true);
                     break;
        }
    }
    
    private void cargarPrograma(){
        try {
            String sql = "SELECT * FROM programa order by descripcion ";
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            cboPrograma.removeAllItems();
            while (z.rs.next()) {
                cboPrograma.addItem(z.rs.getString("descripcion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void addactive(){
        if(!txtArticulo.getText().equals("") & !txtCantidad.getText().equals("")){
            btnAdd.setEnabled(true);
        }
    }
    
    
    private void insertar(){
        try {
            String usr = "select id from usuario where username like '%"+FrmAcceso.usuario+"%'";
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(usr);
            z.rs.next();
            int idus = Integer.parseInt(z.rs.getString("id"));
            
            int area = z.buscaCod("select id from area where descripcion like '%"+cboArea.getSelectedItem().toString()+"%'");
            int rubro = z.buscaCod("select id from rubro where descripcion like '%"+cboRubro.getSelectedItem().toString()+"%'");
            int programa = z.buscaCod("select id from programa where descripcion like '%"+cboPrograma.getSelectedItem().toString()+"%'");
            
            String sql = "INSERT INTO solicitud (nro, fechasol, fechaentrega, descripcion, estado, usrsol,"+
                    "usrarpo, area, rubro, programa) VALUES ("+
                    txtNumero.getText()+", now(),'0000-00-00', '"+txtDescripcion.getText().toString()+"', 1, "+
                    idus+", 5, '"+area+"', "+rubro+", "+programa+")";
            
            z.snt = z.con.createStatement();
            z.snt.executeUpdate(sql);
            
            String id = "SELECT max(id) as id FROM solicitud limit 1";
            
            for( int i = 0; i < Tabla.getRowCount(); i++){
                String item = "INSERT INTO item (articulo, solicitud, cantidad) VALUES ("+
                        modelo.getValueAt(i, 0)+", ("+id+") ,"+modelo.getValueAt(i, 2)+")";
                System.out.print(item);
                z.snt = z.con.createStatement();
                z.snt.executeUpdate(item);
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmSolicitud().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlDescripcion;
    private javax.swing.JPanel PnlSolicitud;
    private javax.swing.JPanel PnlTipo;
    private javax.swing.JRadioButton RbBien;
    private javax.swing.JRadioButton RbServicio;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboArea;
    private javax.swing.JComboBox cboPrograma;
    private javax.swing.JComboBox cboRubro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrograma;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblRubro;
    private javax.swing.JLabel lblRubro1;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtResponsable;
    // End of variables declaration//GEN-END:variables
}
